### ISSUE TITLE
Emails are triggered, also if you dont want them

### ISSUE THREAD

**Issue by galadril** [NiekNijland/RTX3000-notifier#1]
First of all, thanks for this cool service.!

But i noticed that im getting 3070/3090 emails while i only whitelisted 3080 email.

**Comment by galadril** [comment]
Subscribe settings:
![image](https://user-images.githubusercontent.com/14561640/100232954-5ae42d80-2f29-11eb-9776-2e321ca9dc54.png)

What i just received:
![image](https://user-images.githubusercontent.com/14561640/100233017-70595780-2f29-11eb-9af4-b7c6fe18d61d.png)

**Comment by NiekNijland** [comment]
Hi  @galadril, thanks for your response. I have noticed this as well and will look into it tonight / tomorrow. I have shut down the backend for now, because I don't want to send all the subscribers unnecessary emails, especially if the unsubscribe functionality is not working.

**Comment by galadril** [comment]
this code now checks if the subscriber has an interest:
![image](https://user-images.githubusercontent.com/14561640/100243577-4f4b3380-2f36-11eb-9721-514626e74006.png)

**Comment by galadril** [comment]
It should work.. i couldnt check it because i miss the subscriber database ..
I just setup a mongodb for testing the websites 🗡️

**Comment by galadril** [comment]
Maybe another idea, you could easely port this to an Azure Function.. and let it run time based in a free azure cloud account..

**Comment by NiekNijland** [comment]
@galadril yes I see, I forgot to put an if-statement there because I was originally planning to only fetch interested subscribers from the database, but got stuck and decided to just go with a code based solution. I build the backend + frontend in 1 day, so maybe didn't do the cleanest job :)
