### ISSUE TITLE
Add link to the product page

### ISSUE THREAD

**Issue by galadril** [NiekNijland/RTX3000-notifier#2]
A feature request for the emails. Please link the direct product page where we can buy the card.
Now it contains a link like: 
https://cdromland.nl/

But it could be:
https://cdromland.nl/product/942/1119242/Nvidia-Videokaarten/Asus-Geforce-RTX-3080-ROG-STRIX-RTX3080-10G-GAMING-Videokaart

**Comment by NiekNijland** [comment]
Hi @galadril, stock is not tracked from the product page(s) but from the overview of all products, so I have no records on which card has been stocked when you recieve an email.

**Comment by galadril** [comment]
If somebody gets a notification, the number of steps to Buy the card should be as low as possible...
So maybe then open the shop with filters for the specific card..? and filter out the out of stock ones?


For example, an email for **informatique** for an available 3090>
https://www.informatique.nl/?m=sts&g=166&p=&sort=&ss=2&pr_min=&pr_max=&at529=27549



**or Megekko:**
3070 link:
https://www.megekko.nl/Computer/Componenten/Videokaarten/Nvidia-Videokaarten/Graphics-Engine/GeForce-RTX-3070?f=f_vrrd-0_s-populair_pp-50_p-1_d-list_cf-

3080 link:
https://www.megekko.nl/Computer/Componenten/Videokaarten/Nvidia-Videokaarten/Graphics-Engine/GeForce-RTX-3080?f=f_vrrd-1_s-populair_pp-50_p-1_d-list_cf-

3090 link:
https://www.megekko.nl/Computer/Componenten/Videokaarten/Nvidia-Videokaarten/Graphics-Engine/GeForce-RTX-3090?f=f_vrrd-1_s-populair_pp-50_p-1_d-list_cf-

**Comment by NiekNijland** [comment]
@galadril yeah that is a good option. I'm already doing that for some shops when you click the link in the frontend, but I haven't done that for the emails yet.

**Comment by galadril** [comment]
Made a PR for it.. couldnt find the cdromland product specific pages.. but i did for all the others.
Let me know if i can help more ;)
